# 什么是NumPy

Numpy提供了多为数组对象, 用于数组快速操作的各种API. NumPy包的核心是`ndarry`对象. 封装了Python原生的同数据类型的n维数组, 为了保证其性能, 其中有许多操作都是代码在本地进行编译后执行的.
NumPy数组和原生Python Array之间的几个重要区别:
1. NumPy数组在创建时具有固定的大小, 而Python Array是可以动态增长的. 更改ndarray的大小将创建一个新数组并删除原来的数组
2. NumPy数组中的元素都需具有相同的数据类型, 因此在内存中大小相同

## 基础知识

1. `ndarray.ndim`: 数组的轴的个数, 其实就是**rank**
2. `ndarray.shape`: 数组的维度, 对于n行m列的数组, 维度就是(n, m)
3. `ndarray.size`: 数组元素的总数, shape元组的乘积
4. `ndarray.dtype`: 描述数组中元素类型的对象. NumPy提供的类型不用于Python, 例如由`numpy.int32`, `numpy.int16`, `numpy.float64`
5. `ndarray.itemsize`: 数组中每个元素的字节大小, 例如`float64`类型的数组为8, 而`complex32`类型的数组为4

In [10]:
import numpy as np
# 创建包含0-14, 维度为(3, 5)的数组
a = np.arange(15).reshape(3, 5)
print("数组a的维度是: ", a.shape)
print("数组a的rank是: ", a.ndim)
print("数组a内的元素类型是: ", a.dtype.name)
print("数组a内的元素字节大小: ", a.itemsize)
print("数组a内元素的个数: ", a.size)
a

数组a的维度是:  (3, 5)
数组a的rank是:  2
数组a内的元素类型是:  int32
数组a内的元素字节大小:  4
数组a内元素的个数:  15


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 数组创建

可以使用array函数从Python*列表*或*元组*中创建数组. 得到的数组的类型是从Python列表中元素的类型推导出来的

In [17]:
# 通过array创建数组, 传输的应该是个可迭代对象, 比如元组或列表, 不能是一堆数字
b = np.array([1, 2, 3, 4])
print(b.dtype)
# 还可以将序列的序列转换成二维数组, 或是将序列的序列的序列转换成三维数组......
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
# 也可以在创建时显式指定数组的类型
d = np.array([[1, 2], [3, 4]], dtype=complex)
d

int32
[[1 2 3]
 [4 5 6]]


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [25]:
# zeros, 创建一个完全由0组成的数组
np.zeros((3, 4))
# ones, 创建一个完全由1组成的数组
np.ones((2, 3, 4), dtype=np.int16)
# empty, 创建一个数组, 不过初始内容完全随机
np.empty((2, 3))

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

也可以通过迭代的方式创建数组, 比如`arange`或者`linspace`
如果创建的数组元素都是整数, 那就用`arange`
如果创建的数组元素是浮点数, 那就用`linspace`

In [29]:
# start, end, step
np.arange(10, 30, 5)
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [31]:
from numpy import pi
# generate 9 numbers, from 0 to 2
print(np.linspace(0, 2, 9))
x = np.linspace(0, 2 * pi, 100)
print(np.sin(x))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.1367739

### 基本操作

In [36]:
a = np.array([20, 30, 40, 50])
b = np.arange(0, 4, 1)
print(a - b)
print(b ** 2)

[20 29 38 47]
[0 1 4 9]


In [38]:
# 普通乘法与点乘
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
print(A * B)
print(A @ B)
print(A.dot(B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


### 索引, 切片和迭代

In [45]:
# ndarry当然可以像Python可迭代对象一样进行索引, 切片和迭代操作
a = np.arange(10) ** 3
print(a)
print("索引2的元素是: ", a[2])
print("索引2到索引4的元素都有: ", a[2:5])
# 等同于a[0:6:2]
a[0:6:2] = -1000
print(a)
# 数组逆置
print(a[::-1])

[  0   1   8  27  64 125 216 343 512 729]
索引2的元素是:  8
索引2到索引4的元素都有:  [ 8 27 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]
