# 数组的形状操纵

## 改变数组的形状

In [3]:
import numpy as np
# 随机生成(3, 4)的数组
a = np.floor(10*np.random.random((3,4)))
print(a)

[[5. 5. 0. 9.]
 [3. 6. 7. 3.]
 [2. 8. 9. 5.]]


In [9]:
# 以下的三个方法并不会实际改变内存中的数组对象
# 只是将新修改的数组对象加以返回
# 将多维数组压缩成一个一维数组, 并返回
print(a.ravel())
# 返回一个新修订的数组
print(a.reshape(6, 2))
# 转置矩阵
print(a.T)
print(a.T.shape)

[5. 5. 0. 9. 3. 6. 7. 3. 2. 8. 9. 5.]
[[5. 5.]
 [0. 9.]
 [3. 6.]
 [7. 3.]
 [2. 8.]
 [9. 5.]]
[[5. 3. 2.]
 [5. 6. 8.]
 [0. 7. 9.]
 [9. 3. 5.]]
(4, 3)


In [12]:
# ndarray.resize方法会修改数组本身
a.resize((2, 6))
print(a)

[[5. 5. 0. 9. 3. 6.]
 [7. 3. 2. 8. 9. 5.]]


## 将不同数组堆叠在一起

In [20]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
# 纵向合并
print("把数组a和b纵向放置后: ", np.vstack((a, b)))
# 横向合并
print("把数组a和b横向放置后: ", np.hstack((a, b)))

把数组a和b纵向放置后:  [[2. 9.]
 [1. 2.]
 [0. 2.]
 [1. 1.]]
把数组a和b横向放置后:  [[2. 9. 0. 2.]
 [1. 2. 1. 1.]]


## 将一个数组拆分成几个较小的数组

In [18]:
a = np.floor(10*np.random.random((2,12)))
print(a)
# 使用hsplit, 可以沿数组的水平轴拆分数组
print(np.hsplit(a, 3))
print(np.hsplit(a, (3, 4)))

[[1. 9. 9. 7. 5. 0. 5. 0. 1. 2. 6. 4.]
 [1. 2. 5. 1. 6. 9. 2. 1. 7. 5. 7. 1.]]
[array([[1., 9., 9., 7.],
       [1., 2., 5., 1.]]), array([[5., 0., 5., 0.],
       [6., 9., 2., 1.]]), array([[1., 2., 6., 4.],
       [7., 5., 7., 1.]])]
[array([[1., 9., 9.],
       [1., 2., 5.]]), array([[7.],
       [1.]]), array([[5., 0., 5., 0., 1., 2., 6., 4.],
       [6., 9., 2., 1., 7., 5., 7., 1.]])]
