# Numpy基础用法
一个`Numpy`数组是一个由值组成的网格, 所有值都是相同的数据类型, 其维数就是`rank`, 数组的维度是一个由整数组成的元组, 代表了数组每个维度的大小

In [14]:
import numpy as np
# 创造一个一维数组
a = np.array([1, 2, 3])
print("a的数据类型: ", type(a))
# 如果是一维数组, shape[0]直接代表元素的个数, 没有shape[1]
# 如果是二维数组, shape[0]代表了数组的行数, shape[1]代表了数组的列数, shape[-1]代表最后一个维度, 就是数组的列数
print("a第一维度的长度: ", a.shape[0])
print("a的维度: ", a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print("改变后的a数组: ", a)

b = np.array([[1, 2, 3], [4, 5, 6]])
print("b的维度: ", b.shape)
print("b第一维度的长度: " , b.shape[0])
print(b[0, 0], b[0, 1], b[1, 0])

a的数据类型:  <class 'numpy.ndarray'>
a第一维度的长度:  3
a的维度:  (3,)
1 2 3
改变后的a数组:  [5 2 3]
b的维度:  (2, 3)
b第一维度的长度:  2
1 2 4


In [26]:
# 创造一个全为0的矩阵
a = np.zeros((2, 2))
print(a)

b = np.zeros((1, 2))
print(b)

# 创建一个只有一种元素的数组
c = np.full((2, 2), 7)
print(c)

# 创建一个特定大小的单位矩阵
d = np.eye(2)
print(d)

# 创建一个由随机数组成的数组
e = np.random.random((2, 2))
print(e)

[[0. 0.]
 [0. 0.]]
[[0. 0.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.76915092 0.0421865 ]
 [0.15463751 0.36003397]]


## 数组索引

In [34]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# b取a的第0行到第1行, 第1列到第2列
b = a[:2, 1:3]
print(b)

print("a数组中第0行第3列的元素是: ", a[0, 2])
b[0, 0] = 77
print(b)

[[2 3]
 [6 7]]
a数组中第0行第3列的元素是:  3
[[77  3]
 [ 6  7]]


In [40]:
# 索引和切片混用
row_r1 = a[1, :]
print("a数组中索引为1的行数中的所有元素: ", row_r1)
row_r2 = a[1:2, :]
print(row_r2)
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"
print(a)
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1)
print(col_r2)

a数组中索引为1的行数中的所有元素:  [5 6 7 8]
[[5 6 7 8]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[77  6 10]
[[77]
 [ 6]
 [10]]
