# 自动微分

In [26]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [27]:
x.requires_grad_(True)
x.grad

In [28]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [29]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [31]:
# 正常情况加会积累梯度，需要清空
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

## 非标量变量的反向传播

In [32]:
# 如果y不是标量时，向量y关于向量x的导数是一个矩阵。对于高阶和高维的y和x，求导的结果可以是一个高阶张量
# 对非标量调用backward需要传入一个gradient参数，该参数指定微分函数关于self的梯度。
# 本例只想求偏导数的和，所以传递一个1的梯度是合适的
x.grad.zero_()
y = x * x
# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])