# 数据操作与数据预处理

In [3]:
import torch

In [4]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
# 张量形状
x.shape

torch.Size([12])

In [6]:
# 统计张量中的元素个数
x.numel()

12

In [8]:
# 改变张量的形状
# 在改变张量的形状时，可以不手动指定每个维度来改变形状
# 比如x.reshape(3, -1), x.reshape(-1, 4), 跟x.reshape(3, 4)是一样的
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
torch.rand((2, 3, 4))

tensor([[[0.1769, 0.1680, 0.3895, 0.8776],
         [0.8123, 0.3994, 0.1447, 0.2383],
         [0.5169, 0.6515, 0.9507, 0.7797]],

        [[0.0715, 0.8672, 0.7113, 0.9246],
         [0.9324, 0.9511, 0.4935, 0.0734],
         [0.3083, 0.1369, 0.1053, 0.9838]]])

In [12]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [14]:
# 求幂运算
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [19]:
# 将多个张量连结，端对端叠起来
# dim=0, 按行连结矩阵
# dim=1, 按列连结矩阵
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y, torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [20]:
# 逻辑运算符
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [23]:
# 对张量内所有元素进行求和
X.sum(), Y.sum()

(tensor(66.), tensor(30.))

## 广播机制

In [28]:
# 即使形状不同，仍可以通过广播机制来执行按元素操作
# 1. 通过适当复制元素来扩展数组，以便在转换之后，两个张量具有相同的形状
# 2. 对生成的数组执行按元素操作
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [29]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 索引和切片

In [32]:
# 张量的元素可以通过索引来访问
X[-1], X[1:3], X[1:3, 1:4]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 5.,  6.,  7.],
         [ 9., 10., 11.]]))

In [33]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [34]:
# 为多个元素赋值相同的值
# 为X张量的，所有第一行，第二行的元素赋值为12
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 节省内存

In [35]:
# Y = X + Y, 取消引用Y指向的张量，而是指向新分配的内存处的张量
before = id(Y)
print("Y张量一开始的内存id: ", before)
Y = X + Y
print("后来的Y张量的内存id: ", id(Y))

Y张量一开始的内存id:  1830595510416
后来的Y张量的内存idL  1830964176352


In [39]:
# 为什么改进？
# 在ML中，要避免不必要分配内存，比如backward forward, 还是希望原地更新
# 执行原地操作是个好办法，使用切片表示法
Z = torch.zeros_like(Y)
print('id(Z): ', id(Z))
Z[:] = X + Y
print('id(Z): ', id(Z))

id(Z):  1830977687200
id(Z):  1830977687200


In [40]:
# 或者干脆如下
before = id(X)
print("X张量一开始的内存id: ", before)
X += Y
print("后来的X张量的内存id: ", id(X))

X张量一开始的内存id:  1830952523632
后来的X张量的内存id:  1830952523632


## 与Python对象之间的转换

In [44]:
# tensor to ndarray
A = X.numpy()
# ndarray to tensor
B = torch.tensor(A)
type(A), type(B)

(torch.Tensor, torch.Tensor)

In [45]:
# 将大小为1的张量转换为Python数值
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 数据预处理

In [49]:
import os

os.mkdir(os.path.join('.', 'data'))
data_file = os.path.join('.', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [52]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


## 处理缺失值

In [57]:
# 插值法，用一个替代值弥补缺失值
# 删除法，直接忽略缺失值
# iloc，位置索引
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

TypeError: can only concatenate str (not "int") to str

In [61]:
# get_dummies: one-hot-encode
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       NaN        True      False
1       2.0       False       True
2       4.0       False       True
3       NaN       False       True


## 转换为张量格式

In [62]:
import torch
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
X, y

(tensor([[nan, 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [nan, 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))